service: everymundo
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
functions:
  newlogemail:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: test-lambda-bucket-for-every-mundo
          event: s3:ObjectCreated:*
          existing: true
#    layers:
#      - arn:aws:lambda:us-east-1:240758252060:layer:main_py:1
#      - arn:aws:lambda:us-east-1:240758252060:layer:pandas:1

# Lines 14-16 are my attempt at attaching layers which I added in my AWS account
# main_py would allow me to use functions in main.py
# pandas would allow me to import pandas and create DataFrames
# attaching pandas to the lambda kept giving me this error "Function code combined with layers exceeds the maximum
# allowed size of 262144000 bytes. The actual size is 282544825 bytes." I was unable to resolve that issue.


